### ISSUE TITLE
get_tip.py中的f.write文件编码问题

### ISSUE THREAD

**Issue by qaqFei** [ssmzhn/Phigros#1]
![捕获](https://github.com/ssmzhn/Phigros/assets/158535495/e290ef03-117e-4c15-9f50-f2083d598fdd)

添加,encoding='utf-8'即可

with open('tips.json','w',encoding='utf-8') as f:
    f.write(json.dumps(tip_info,indent=4,ensure_ascii=False))

**Comment by sakimidare** [comment]
感谢Issue！

我主要是用 Termux 测试的，没在 Windows 上跑过，可能会有大大小小的编码问题。

~~顺便提一句 Windows 的编码就是史~~

**Comment by sakimidare** [comment]
已修改，再次感谢提醒！
手上暂时没有 Windows 设备，issue先关了，有bug的话可以再开
